<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBAdapter/Project2/ServicesLogging" name="ServicesLogging-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DBAdapter/Project2/ServicesLogging" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBAdapter/Project2/ServicesLogging" location="../Resources/wsdl/ServicesLogging.wsdl"/>
  <binding name="ServicesLogging_ptt-binding" type="tns:ServicesLogging_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="ServicesLogging-service">
    <port name="ServicesLogging-port" binding="tns:ServicesLogging_ptt-binding">
      <soap:address location="jca://eis/DB/srvlyr_logmsgs"/>
    </port>
  </service>
</definitions>